' Gambas module file

Public Settings As New Settings(Application.Path & "/Cerbero.settings")
Private $Connection As New Connection
Public Sub Main()
  Dim DPath As String
  Dim dDate As Date

  Session.CookiePath = "/"

  'Session.Load()

  OpenDatabase()
  
  'CSS.Main()
  Select Case MPath.Section
    Case MPath.PATH_ADMIN
      If Session["role"] = "admin" Then
        Response.ContentType = "text/html;charset=utf-8"
        Response.Begin
        WAdmin.Render
        Response.End  
      Else
        Response.Redirect("/")
      Endif
    Case MPath.PATH_LOGOUT
      If Session.Id Then
        Session.Abandon
      Endif
      Response.AddHeader("Content-Type", "text/html; charset=UTF-8")
      Response.Redirect("/")
    Case MPath.PATH_PROFILE
      If Session.Id Then
        Response.ContentType = "text/html;charset=utf-8"
        Response.Begin
        WProfile.Render
        Response.End  
      Else
        Response.Redirect("/")
      Endif
    Case MPath.PATH_LOGIN
      If Session.Id Then
        Session.Abandon
      Endif
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin()
      WLogin.Render
      Response.End()
    Case MPath.PATH_LOGIND
      MLogin.Login()
    Case MPath.PATH_CONFIRM
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
      WConfirm.Render
      Response.End
    Case MPath.PATH_REGISTER
      If Session.Id Then
        Session.Abandon
      Endif
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
      WRegister.Render
      Response.End
    Case MPath.PATH_REGISTERD
      MRegister.Register()
    Case MPath.PATH_NEWS
      Response.ContentType = "text/html;charset=utf-8"
      Response.begin
      WBlogIndex.Render
      Response.End
    Case MPath.PATH_POSTS
      If Session["role"] = "admin" Then
        Response.ContentType = "text/html;charset=utf-8"
        Response.begin
        WWriter.Render
        Response.End
      Else
        Response.Redirect("/")
      Endif
    Case MPath.PATH_CPUDB
        Response.ContentType = "text/html;charset=utf-8"
        Response.begin
        CPUDBindex.Render
        Response.End
    Case MPath.PATH_PUBLIC
      MPublic.INIT
    Case MPath.PATH_MAIN, MPath.PATH_404
      Response.ContentType = "text/html;charset=utf-8"
      Response.begin
      WIndex.Render
      Response.End
  End Select
  'Session.Save()

Catch
  
  Response.ContentType = "text/html;charset=UTF-8"
  
  Print "<html><body><h2>Unexpected error while displaying this page.</h2>"
  Print "<pre>"; Error.Text, Error.Code
  Print "<b>"; Error.Where; "</b>"
  Print "<p>"; Error.Backtrace.Join("<br />"); "</p>"
  
  Debug()
  
  Print "</pre></body>"

End

Public Function USER_AVATAR_PATH() As String

  Dim USER_PROFILE_DATA As Collection
  Dim USERNAME As String

  If Session.Id Then
    USERNAME = Session["username"] 
    USER_PROFILE_DATA = JSON.Decode(File.Load(Application.Path & "/Users/" & USERNAME & "/config.json"))
    If USER_PROFILE_DATA["avatar"] = "True" Then
      Return "/.avatars/" & USER_PROFILE_DATA["username"] & "/avatar.png"
    Else
      Return ""
    Endif
  Endif

End

Private Sub Debug()

  Print "<br />"
  Print "<br />"
  Print "Application.Host: " & Application.Host & "<br />"
  Print "Application.Request: " & Application.Request & "<br />"
  Print "Request.Path: " & Request.Path & "<br />"
  'Print "Path.Page: " & Path.Page & "<br />"
  'Print "Language: " & Me.Language & "<br /><br />"

  ' Print "Users.Current.Username: " & User.Current.Username & "<br />"
  ' Print "Users.Current.IsAdmin: " & Users.Current.IsAdmin & "<br />"
  ' Print "Users.Current.Type: " & Users.Current.Type & "<br /><br />"

  Print "Session.Username: " & Session["username"] & "<br />"
  Print "Session.id: " & Session.Id & "<br /><br />"

  ' Print "Actions.Parsed: " & Actions.Parsed & "<br />"
  ' Print "Actions.Show: " & Actions.Show & "<br />"
  ' Print "Actions.View: " & Actions.View & "<br />"
  ' Print "Actions.Edit: " & Actions.Edit & "<br />"
  ' Print "Actions.Help: " & Actions.Help & "<br />"
  ' Print "Actions.OnlineHelp: " & Actions.OnlineHelp & "<br />"
  ' Print "Actions.Image: " & Actions.Image & "<br />"
  ' Print "Path.Section: " & Path.Section & "<br /><br />"
  ' 
  ' Print "Wget: " & Main.IsWget & "<br />"

End

Public Sub OpenDatabase()
  
  $Connection = Connections["Cerbero"]
  $Connection.Host = Settings["mysql/host"]
  $Connection.Password = Settings["mysql/password"]
  Try $Connection.Open
  If Error Then
    CGI.Error(Error.Text)
  Endif
  DB.Current = $Connection
  
End
