' Gambas module file

Public Settings As New Settings(Application.Path & "/Cerbero.settings")
Private $Connection As New Connection
Public Sub Main()
  Dim DPath As String
  Dim dDate As Date

  $Connection = Connections["Cerbero"]
  $Connection.Host = Settings["mysql/host"]
  $Connection.Password = Settings["mysql/password"]
  $Connection.Open
  DB.Current = $Connection
  
  'CSS.Main()
  Select Case MPath.Section
    Case MPath.PATH_ADMIN
      If Session["role"] = "admin" Then
        Response.ContentType = "text/html;charset=utf-8"
        Response.Begin
        WAdmin.Render
        Response.End  
      Else
        Response.Redirect(Application.Root)
      Endif
    Case MPath.PATH_LOGOUT
      If Session.Id Then
        Session.Abandon
      Endif
      Response.AddHeader("Content-Type", "text/html; charset=UTF-8")
      Response.Redirect(Application.Root)
    Case MPath.PATH_PROFILE
      If Session.Id Then
        Response.ContentType = "text/html;charset=utf-8"
        Response.Begin
        WProfile.Render
        Response.End  
      Else
        Response.Redirect(Application.Root)
      Endif
    Case MPath.PATH_LOGIN
      If Session.Id Then
        Session.Abandon
      Endif
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin()
      WLogin.Render
      Response.End()
    Case MPath.PATH_LOGIND
      MLogin.Login()
    Case MPath.PATH_CONFIRM
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
      WConfirm.Render
      Response.End
    Case MPath.PATH_REGISTER
      If Session.Id Then
        Session.Abandon
      Endif
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
      WRegister.Render
      Response.End
    Case MPath.PATH_REGISTERD
      MRegister.Register()
    Case MPath.PATH_PUBLIC
      MPublic.INIT
    Case MPath.PATH_MAIN
      Response.ContentType = "text/html;charset=utf-8"
      Response.begin
      WIndex.Render
      Response.End
  End Select

End

Public Function USER_AVATAR_PATH() As String

  Dim USER_PROFILE_DATA As Collection
  Dim USERNAME As String

  If Session.Id Then
    USERNAME = Session["username"] 
    USER_PROFILE_DATA = JSON.Decode(File.Load(Application.Path & "/Users/" & USERNAME & "/config.json"))
    If USER_PROFILE_DATA["avatar"] = "True" Then
      Return "/.avatars/" & USER_PROFILE_DATA["username"] & "/avatar.png"
    Else
      Return ""
    Endif
  Endif

End
