' Gambas module file

Export

Property Read Randomkey As String

Private Function Randomkey_Read() As String
  Dim uniqueid As String
  Dim I As Integer
  Randomize
  For I = 1 To 6
       uniqueid &= Hex$(Int(Rnd(65536)), 4)
  Next
  Return uniqueid
End

Public Function CheckEMail(email As String) As Boolean

  'Dim regex As New Regexp(email, "^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$")
  'RegExp.Match(email, "^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$")
  Return RegExp.Match(email, "^[a-z0-9._-]+@[a-z0-9._-]{2,}\\.[a-z]{2,4}$")

End

Public Function IsMimeType($file As String, ...) As Boolean
  
  Dim data, s As String
  Exec ["file", "-i", $file] To data
  
  For Each s In Param
    If InStr(data, s) Then Return True
  Next
  
  Return False
  
End

Public Function GravatarAV(email As String, Optional Size As String) As String
  Dim AVHash As String
  Dim $URL As String = "https://secure.gravatar.com/avatar/"
  'AVHash = LCase(Crypt.MD5(email))
  'AVHash = LCase(Base64$(Digest["md5"](email)))
  Shell "echo -n " & email & " | tr '[:upper:]' '[:lower:]' | md5sum" Wait To AVHash
  AVHash = Replace(Replace(Replace(Replace(AVHash, "\t", ""), "-", ""), "\n", ""), " ", "")
  If IsNull(Size) Then
    Return $URL & AVHash
  Else
    Return $URL & AVHash & "?s=" & Size
  Endif
End

Public Function DisqusAV(username As String)
  Dim hClient As HttpClient
  Dim sBuffer As String

  hClient = New HttpClient As "hClient"
  hClient.URL = "https://disqus.com/api/users/avatars/" & username & ".jpg"
  hClient.Async = False
  hClient.Timeout = 60
  hClient.Get
  Print #hClient, Lof(hClient)
  ' Print "Begin"
  ' If hClient.Status < 0 Then
  '   Print "ERROR"
  ' Else
  '   ' Success - read the data
  '   If Lof(hClient) Then sBuffer = Read #hClient, Lof(hClient)
  '   Print sBuffer
  ' End If
  ' 
  ' Print "end"
  
  
End
