' Gambas module file

Public Sub Main()
  Dim sEnv As String
   Select Case Request.Path
    Case "/logout"
       If Session.Id Then
         Session.Abandon
       Endif
       Response.AddHeader("Content-Type", "text/html; charset=UTF-8")
       Response.Redirect(Application.Root)
    Case "/confirm" ' confirm registration
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
            WConfirm.Render
      Response.End
    Case "/profile" ' publish software  
      If Session.Id Then
            Response.ContentType = "text/html;charset=utf-8"
            

            Response.Begin
                    WProfile.Render
            Response.End  
      Else
            Response.Redirect(Application.Root)
      Endif
      
      
    Case "/admin" ' get info about software
      If Session["role"] = "admin" Then
             Response.ContentType = "text/html;charset=utf-8"
             Response.Begin
                    WAdmin.Render
             Response.End  
      Else
             Response.Redirect(Application.Root)
      Endif
      
    Case "/login"
       If Session.Id Then
         Session.Abandon
       Endif

       Response.ContentType = "text/html;charset=utf-8"
       Response.Begin()
             WLogin.Render
       Response.End()

    Case "/logind"
       MLogin.Login()
    Case "/register" ' register a new account
      If Session.Id Then
         Session.Abandon
      Endif
      Response.ContentType = "text/html;charset=utf-8"
      Response.Begin
      WRegister.Render
      Response.End
    Case "/registerd" ' download software
       MRegister.Register()
    Case "/ident"
      Response.Begin
      Print MFunctions.getrandom()
      Response.End
    Case "/dba"
        Response.ContentType = "text/plain;charset=utf-8"
        Response.begin
        Print Request.Path
        Print Application.Path &/ ".public" & Request.Path
        Print Application.Path
        Print Application.Root
        Print Application.Root
        
        For Each sEnv In Application.Env
          Print sEnv & Application.Env[sEnv]
        Next
        Response.End    
    Case "/"
      Response.ContentType = "text/html;charset=utf-8"
      Response.begin
      WIndex.Render
      Response.End    
  End Select
  Catch
    Response.Begin
    Print "12 Unexpected error\n\n" & Error.Text & "\n\n" & Error.Backtrace.Join("\n")
    Response.End
End
