' Gambas module file

Public Sub Login()
  Dim USERNAME As String = Request.Post["username"]
  Dim PASSWORD As String = Request.Post["password"]
  Dim rUser As Result
   
  If Not USERNAME Then
    Response.Redirect("/login?alert=1")
    Return
  Endif
  If Not PASSWORD Then
    Response.Redirect("/login?alert=2")
    Return
  Endif
  
  rUser = DB.Edit("users", "username = &1", USERNAME)
  If Not rUser.Available Then
    Response.Redirect("/login?alert=4")
    Return
  Endif
  
  If rUser!emailVerified = False Then
    Response.Redirect("/login?alert=4")
  Endif
  
  If rUser.Available Then
    If rUser!password = Base64$(Digest["sha256"](PASSWORD)) Then
       Session.CookiePath = "/"
       Session["username"] = rUser!username
       Session["role"] = rUser!role
       Session["firstname"] = rUser!firstname
       Session["lastname"] = rUser!lastname
       Session["email"] = rUser!email
       Session["avatar"] = rUser!avatar
       Session["emailVerified"] = rUser!emailVerified
       Session["verificationToken"] = rUser!verificationToken
       Session.Timeout = 86400 + 1000
       Response.Redirect("/")
    Else
      Response.Redirect("/login?alert=4")
    Endif
  Endif
End
